apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260626-135110-qvt9bb5tsepq-service
spec:
  selector:
    app: enterprise-system-20260626-135110-qvt9bb5tsepq
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
